# Generated by Django 3.2.7 on 2021-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('mechanical', 'Mechanical'), ('civil', 'Civil'), ('electrical', 'Electrical'), ('electronics', 'Electronics'), ('computer', 'Computer'), ('pharmacy', 'Pharmacy')], max_length=50, null=True),
        ),
    ]
