# Generated by Django 3.2.7 on 2021-10-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_join',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
