# Generated by Django 3.2.7 on 2021-10-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_date_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
    ]
