# Generated by Django 3.2.7 on 2021-10-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activity/file/'),
        ),
    ]
