# Generated by Django 3.2.7 on 2021-10-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211005_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='semester',
        ),
        migrations.AddField(
            model_name='semester',
            name='attendance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
